lnksys=typeof(lnksys)=='undefined'?{}:lnksys;
lnksys.server=typeof(lnksys.server)=='undefined'?{}:lnksys.server;
lnksys.server.logger=typeof(lnksys.server.logger)=='undefined'?{}:lnksys.server.logger;
lnksys.server.logger.logbuf=typeof(lnksys.server.logger.logbuf)=='undefined'?{}:lnksys.server.logger.logbuf;
lnksys.server.logger.logbuf.buf=typeof(lnksys.server.logger.logbuf.buf)=='undefined'?[]:lnksys.server.logger.logbuf.buf;
lnksys.server.logger.logbuf.last=typeof(lnksys.server.logger.logbuf.last)=='undefined'?'':lnksys.server.logger.logbuf.last;
lnksys.server.logger.logbuf.sending=typeof(lnksys.server.logger.logbuf.sending)=='undefined'?false:lnksys.server.logger.logbuf.sending;
lnksys.server.logger.log=function(msg,url,line){
	msg=msg==null?'':msg; 
	url=url==null?'':url; 
	line=line==null?'':line; 
	if(!lnksys.server.logger.logbuf.sending){
		if(msg!=lnksys.server.logger.logbuf.last){
			lnksys.server.logger.logbuf.sending=true;
			$.ajax(
				'/log.js',
				{
					data:JSON.stringify({'lognode':'client','url':url,'msg':msg,'line':line}),
					contentType:'application/json',
					type:'POST'
				}
			).done(
				$.proxy(function(data){
					lnksys.server.logger.logbuf.sending=false;
				},this)
			).fail(
				$.proxy(function(){
					lnksys.server.logger.logbuf.sending=false;
				},this)
			).always(
				$.proxy(function(){
					var nxt=lnksys.server.logger.logbuf.buf.pop();
					if(nxt!=null)
						lnksys.server.logger.log(
							nxt.msg,
							nxt.url,
							nxt.line
						);
				},this)
			)
		}else{
		}
		lnksys.server.logger.logbuf.last=msg;
	}else{
		//lnksys.server.logger.logbuf.buf.push({'msg':msg,'url':url,'line':line});
		lnksys.server.logger.logbuf.buf=[{'msg':msg,'url':url,'line':line}].concat(lnksys.server.logger.logbuf.buf)
	}
};
lnksys.log=lnksys.server.logger.log;
window.onerror=lnksys.server.logger.log;
window.console.log=function(a){
	lnksys.server.logger.log(a);
}
window.console.error=function(a){
	lnksys.server.logger.log(a);
}
window.console.debug=function(a){
	lnksys.server.logger.log(a);
}
