define(
	[
		"dojo/_base/declare",
		"dojo/html",
		"dojo/_base/fx",
		"dojo/_base/lang",
		"dojo/dom-style",
		"dojo/mouse",
		"dojo/on",
		"dijit/_WidgetBase",
		"dijit/_TemplatedMixin",
		"dojo/dom-construct",
		"xstyle/css!./templates/sb-admin-2.min.css",
		"xstyle/css!./templates/fontawesome-free/css/all.min.css",
		"xstyle/css!./templates/Layout.css",
		"dojo/text!./templates/Layout.html"
	],
	function(
		declare,
		html,
		baseFx,
		lang,
		domStyle,
		mouse,
		on,
		_WidgetBase,
		_TemplatedMixin,
		domConstruct,
		sb_admin_2_min_css,
		fontawesome_free_all_min_css,
		css_Layout_css,
		template
	){
		return declare(
			[
				_WidgetBase,
				_TemplatedMixin
			],
			{
				templateString:template,
				sidebar:null,
				topbar:null,
				content:null,
				heading:null,
				headingtxt:null,
				constructor:function(){
				},
				postCreate:function(){
					this.setTitle(this.headingtxt);
				},
				setTitle:function(txt){
					this.headingtxt=txt;
					html.set(
						this.heading,
						this.headingtxt
					);
				}
			}
		);
	}
);

