#!/data/data/com.termux/files/usr/bin/bash
HOST="http://localhost:1111"
CMD="$*"
ls ./scr|while read FILE;do
	BODY='{"cmd":"rm '$FILE'"}'
	curl\
		-H "Content-type: application/json"\
		--data "$BODY"\
		$HOST/xaspost.js
	BODY='{"cmd":"touch '$FILE'"}'
	curl\
		-H "Content-type: application/json"\
		--data "$BODY"\
		$HOST/xaspost.js
	BODY='{"cmd":"save","file":"'$FILE'","contents":"foo"}'
	echo $BODY
	curl\
		-H "Content-type: application/json"\
		--data "$BODY"\
		$HOST/filepost.js
done

